version: '3'

services:
  skess-backend:
    build:
      context: backend
    image: docker-registry.kkoile.de/skess-backend
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS_HOST=skess-db
      - REDIS_PORT=$REDIS_PORT
    links:
      - skess-db
    networks:
      - app-network
    command: ./bin/wait-for.sh skess-db:$REDIS_PORT -- npm start

  skess-db:
    image: redis:alpine
    container_name: skess-db
    restart: unless-stopped
    env_file: .env
    command: --port ${REDIS_PORT} --appendonly yes
    volumes:
      - ~/skess/db:/data
    networks:
      - app-network
  skess-frontend:
    build:
      context: frontend
    image: docker-registry.kkoile.de/skess-frontend
    container_name: skess-frontend
    ports:
      - 4043:443
    networks:
      - app-network
    depends_on:
      - skess-backend

networks:
  app-network:
    driver: bridge
